### PR TITLE
Original pull request was accidentally merged before view

### PR DESCRIPTION
**Pull request by asiimwedismas**
# Milestone 3:

- Added game logic.
- Created Classes and methods.
- Re-arranged Main.rb functionality.

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Impressive work @asiimwedismas :clap: :clap: However, small changes need to be applied in order to get approval for this project. Check :arrow_down: 

- **[REQUIRED]** Use the suitable arrt_* method to encapsulate the attributes ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  - @cells/@winning_combinations in Judge and board classes are exposed to be modified from outside :warning: You used instance methods to access them :100: yet, you gave them **attr_accessor**.
  - Use attr_reader instead because they are accessed from within the classes.

- **[REQUIRED]** :pray: explain why are you working solo in this pull request :mag: 

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by asiimwedismas** [comment]
@stratospherique, sorry but I am not working solo, I just happened to wake up and found my colleague had accidentally merged the original pull request before it had been approved. So I decided to create another and while I was at it I performed some code refactoring,.. Before I knew it, it was 5 commits (couldn't help it 🙈, my bad)

Oh, and we were switching driver/navigator roles between milestones, there are some where I have lik1 or none commits.

**Comment by Bismarck-GM** [comment]
Yep. Exactly that happened. I merged Milestone #4 and forgot that it was created from Milestone #3 . So when I merged the approved one (#4), both got merged into development.

@asiimwedismas just corrected that PR and created a new correct one.
The original commits are inside of the now-closed PR: https://github.com/Bismarck-GM/Microverse-tic-tac-toe/pull/3

**Comment by Bismarck-GM** [comment]
# Milestone 3:

- Changed attribute accessors as TSE pointed out, we only need to read them.
- Learned to not merge until all previous PR's are finished 🥇

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

Thank you for applying all the suggested changes.
You can move forward now.

**PS**: Before merging, please remove `puts/gets` from https://github.com/Bismarck-GM/Microverse-tic-tac-toe/blob/c11cbefd8e056ad1839a32dfed53d3f2d1eb532e/lib/board.rb#L15-L18 because it's not allowed to have `puts/gets` in `lib` folder.

Good continuation :handshake: 

Mael FOSSO

**Comment by Bismarck-GM** [comment]
> # Congratulations 👏
> Thank you for applying all the suggested changes.
> You can move forward now.
> 
> **PS**: Before merging, please remove `puts/gets` from
> 
> https://github.com/Bismarck-GM/Microverse-tic-tac-toe/blob/c11cbefd8e056ad1839a32dfed53d3f2d1eb532e/lib/board.rb#L15-L18
> 
> because it's not allowed to have `puts/gets` in `lib` folder.
> Good continuation 🤝
> 
> Mael FOSSO

Thank you for your review!

Changing the method/function from 'lib' to main.rb in 'bin' before merging.

**Pull request merged**
