### PR TITLE
Milestone 2:

### PR DESCRIPTION
**Pull request by Bismarck-GM**
# Milestone 2:

- Added the basic flow of the game.

### CODE REVIEW

**Comment by uryelah** [comment]
Hi **Dismas Asiimwe & Gero Morisot Morla**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job getting started with this milestone! There are a couple of requirements missing, take a bit of time to read the comments below and think about what you as a tic-tac-toe player would like to have in your game and the best way to display/convey it. You got this! 💪 

# Required Changes 🏗️ 🐛 💡

- [x] The game should verify if a user move is valid, not just if it's between 1-9 but also if the house played is empty or not. Make sure to add that check, even if mocked.

- [x] Display the board before the first play and after each player plays their move. You can already implement the board changing with the play if you want but it can also be mocked.

- [x] The game should informs player if the selected move is a winning move or if the game ended in a tie.


-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Bismarck-GM** [comment]
Requested changes have been made.

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes Required :muscle: 
Hi there team :hand: 
Great job on this milestone so far :clap:  but we still need to work on some requirements pointed out in the last review.

- [x] We need to also verify if a position was already taken and inform the user to pick another one. So it's 2 types of verification, one for invalid input (you already implemented this) and another one to check if the position was taken. You can use one array for that. Create an empty array with a length of 9 and use the corresponding index from the user's input to fill it. This way you can verify if a position was taken or not.

- [x] You need to display the board at the beginning of the game and after each iteration. You do not need to implement anything here, no verifications need to be made, just print an empty board. It does **NOT** need to be printed with updates after each player move. 

- [x] At the last round your app should print a message informing the result of the match. It can be any of these 3: Draw, Player X won, Player O won. It's a mock message so chose any of these.

Kindly submit for code review again after making these changes.
Feel free to message me on Slack with you have questions.

Happy coding :computer: 
**Sergio Torres**

**Comment by asiimwedismas** [comment]
> ### Changes Required 💪
> Hi there team ✋
> Great job on this milestone so far 👏 but we still need to work on some requirements pointed out in the last review.
> 
> * [x]  We need to also verify if a position was already taken and inform the user to pick another one. So it's 2 types of verification, one for invalid input (you already implemented this) and another one to check if the position was taken. You can use one array for that. Create an empty array with a length of 9 and use the corresponding index from the user's input to fill it. This way you can verify if a position was taken or not.
> * [x]  You need to display the board at the beginning of the game and after each iteration. You do not need to implement anything here, no verifications need to be made, just print an empty board. It does **NOT** need to be printed with updates after each player move.
> * [x]  At the last round your app should print a message informing the result of the match. It can be any of these 3: Draw, Player X won, Player O won. It's a mock message so chose any of these.
> 
> Kindly submit for code review again after making these changes.
> Feel free to message me on Slack with you have questions.
> 
> Happy coding 💻
> **Sergio Torres**

Thank you for the clarification, you will be happy to know that all issues raised have been fixed

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great progress :clap: However, small changes need to be applied in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** The game loop isn't DRY enough :warning: , it repeats the same instructions twice in every single iteration.
- **[SUGGESTION]**
```ruby
game_on = true

# initial instructions for player
current_player = player_one
while game_on
  # loop for each move
  # instructions for the current player
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  else
   # switch current_player
  end
end
```
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by Bismarck-GM** [comment]
# Milestone 2:

- Changed loop iteration logic. Applied DRY rules.
- The game now switches between players and breaks out of the loop if any won or all movements were made.

**Review by Forison — APPROVED** [review]
## Status::Approved✔️
# 👋 Team!! 
## Go ahead and merge the branch and proceed to the next milestone.
#### Happy coding
Addo Forison

**Pull request merged**
